name: Maussentials
author: Tulir293
main: net.maunium.bukkit.Maussentials.Maussentials
website: http://maunium.net
version: 0.3
depend: [SQLibrary]
commands:
  maukill:
    description: Kill a player
    aliases: [kill, mauslay, slay]
  mauuuid:
    description: "UUID tools (fetches data from Mojangs' servers)"
    aliases: [uuid, mauuuidtools, uuidtools]
  maugod:
    description: Invincibility
    aliases: [god, maunodamage, nodamage]
  maumessage:
    description: Send a private message
    aliases: [message, maumsg, msg, maupm, pm, mauprivatemessage, privatemessage]
  maureply:
    description: Reply to the last person that sent you a private message
    aliases: [reply, maur, r, maurepl, repl]
  mausocialspy:
    description: Spy on private messages
    aliases: [socialspy, mauss, ss, maumsgspy, msgspy, maupmspy, pmspy]
  maucommandspy:
    description: Spy on private messages
    aliases: [commandspy, maucs, cs, maucmdspy, cmdspy]
  mauseen:
    description: See info about a player
    aliases: [seen, maulastseen, lastseen, mauplayerinfo, playerinfo]
  maureload:
    description: Reload a plugin or a module
    aliases: [maurel, rel, reloader, plugman, maussentials]
  mauplainsay:
    description: Plain broadcast (no prefixes).
    aliases: [plainsay, maupsay, psay, maups, ps, mauplainbroadcast, plainbroadcast, maupb, pb]
  mausignedit:
    description: Edit signs
    aliases: [signedit, mause, se]
  mauplayerdata:
    description: Inspect the data in the PlayerData system.
    aliases: [playerdata, maupd, pd]
  mauban:
    description: "Bananize that damn hacker!"
    aliases: [ban]
  mauwarn:
    description: "Warn that damn hacker!"
    aliases: [warn]
  maustandardban:
    description: Bananize that damn hacker with a predefined message and time
    aliases: [standardban, mausban, sban, maudefaultban, defaultban, maudban, dban]
  mautempban:
    description: "Temporarily bananize that damn hacker!"
    aliases: [tempban, mautban]
  mauunban:
    description: "Unbananize that innocent player that some retard banned!"
    aliases: [unban]
  maubanip:
    description: "Bananize the IP of that damn hacker and/or ban bypasser!"
    aliases: [banip, mauipban, ipban, mauiban]
  mautempbanip:
    description: "Temporarily bananize the IP of that damn hacker and/or ban bypasser!"
    aliases: [tempbanip, mautempipban, tempipban]
  mauunbanip:
    description: "Bananize the IP of that damn hacker and/or ban bypasser!"
    aliases: [unbanip, unipban, mauunipban]
  maubanhistory:
    description: "See how many times you've bananized that damn hacker!"
    aliases: [banhistory, maubanh, banh]
  mautp:
    description: Teleport to a player
    aliases: [tp, mauteleport, teleport]
  mautprequest:
    description: Request to teleport to a player
    aliases: [tprequest, mautpr, tpr, mautpask, tpask, mautpa, tpa]
  mautpaccept:
    description: Accept a teleportation request
    aliases: [tpaccept, mautpyes, tpyes, mautpy, tpy]
  mautpdeny:
    description: Deny a teleportation request
    aliases: [tpdeny, mautpno, tpno, mautpn, tpn]
  # TODO START
  maunick:
    description: Set a players nick
    aliases: [nick, maunickname, nickname]
  mauchannel:
    description: Move to a chat channel
    aliases: [channel, mauch, ch, mauc, c]
  mauchanneladmin:
    description: Manage chat channels
    aliases: [channeladmin, maucha, cha, mauchadmin, chadmin, mauca, ca]
  mauchatformat:
    description: Set the chat format of a group or an user.
    aliases: [chatformat, maucf, cf]
  # TODO BREAK
permissions:
  maussentials.chat.nick:
    description: Set your own nickname.
    default: OP
  maussentials.chat.nick.others:
    description: Set the nickname of another player.
    default: OP
  maussentials.chat.nick.*:
    description: All nickname-related things.
    default: OP
    children:
      maussentials.chat.nick: true
      maussentials.chat.nick.others: true
  maussentials.chat.format:
    description: Set chat format.
    default: OP
  maussentials.chat.format.others:
    description: Set chat format of other players.
    default: OP
  maussentials.chat.format.*:
    description: All chatformat-related things.
    default: OP
    children:
      maussentials.chat.format: true
      maussentials.chat.format.others: true
  maussentials.chat.color:
    description: Use colors in chat
    default: OP
  maussentials.chat.style:
    description: Use style formatting in chat
    default: OP
  maussentials.chat.magic:
    description: Use magic formatting in chat
    default: OP
  maussentials.chat.channel:
    description: Allow switching channels
    default: OP
  maussentials.chat:
    description: Use all chat-related things.
    default: OP
    children:
      maussentials.chat.format.*: true
      maussentials.chat.nick.*: true
      maussentials.chat.color: true
      maussentials.chat.style: true
      maussentials.chat.magic: true
  # TODO END
  # Kill
  maussentials.kill:
    description: Kill a player
    default: OP
  # UUID data
  maussentials.uuid:
    description: "UUID tools (fetches data from Mojangs' servers)"
    default: OP
  # God mode
  maussentials.god:
    description: Invincibility
    default: OP
  maussentials.god.others:
    description: Invincibility
    default: OP
  # Private messaging
  maussentials.message:
    description: Use the private messaging system
    default: true
  maussentials.message.spy:
    description: Spy on private messages
    default: OP
  maussentials.message.color:
    description: Color in private messages
    default: OP
  maussentials.message.style:
    description: Style in private messages
    default: OP
  maussentials.message.magic:
    description: Magic in private messages
    default: OP
  # Command spy
  maussentials.commandspy:
    description: Spy player commands
    default: OP
  # Basic info about a player.
  maussentials.seen:
    description: See info about a player
    default: OP
  # Plugins, modules and reloading.
  maussentials.plugins:
    description: See the plugin list
    default: true
  maussentials.reload:
    description: Allow reloading plugins and modules.
    default: OP
  # Plainsay permissions
  maussentials.plainsay:
    description: Allow use of /mauplainsay
    default: OP
  maussentials.plainsay.see:
    description: See when a plain say message is broadcasted.
    default: OP
  # Playerdata inspect permissions
  maussentials.playerdata:
    description: Inspect the data in the PlayerData system.
    default: OP
  # Sign editing permissions
  maussentials.sign.edit:
    description: Edit signs
    default: OP
  maussentials.sign.format.color:
    description: Color in signs
    default: OP
  maussentials.sign.format.style:
    description: Color in signs
    default: OP
  maussentials.sign.format.magic:
    description: Color in signs
    default: OP
  maussentials.sign.format:
    description: Format signs in any way
    default: OP
    children:
      maussentials.sign.format.color: true
      maussentials.sign.format.style: true
      maussentials.sign.format.magic: true
  # Ban permissions.
  maussentials.bans.use.ban:
    description: Ban a player
    default: OP
  maussentials.bans.use.unban:
    description: Unban a player
    default: OP
  maussentials.bans.use.ipban:
    description: Ban an IP
    default: OP
  maussentials.bans.use.unipban:
    description: Unban an IP
    default: OP
  maussentials.bans.see.ban:
    description: See when a player is banned
    default: true
  maussentials.bans.see.unban:
    description: See when a player is unbanned
    default: true
  maussentials.bans.see.ipban:
    description: See when an IP is banned
    default: OP
  maussentials.bans.see.unipban:
    description: See when an IP is unbanned
    default: OP
  maussentials.bans.see:
    description: See when any kind of a ban/unban is made.
    default: OP
    children:
      maussentials.bans.see.ban: true
      maussentials.bans.see.unban: true
      maussentials.bans.see.ipban: true
      maussentials.bans.see.unipban: true
  maussentials.bans.use:
    description: Use any ban commands
    default: OP
    children:
      maussentials.bans.use.ban: true
      maussentials.bans.use.unban: true
      maussentials.bans.use.ipban: true
      maussentials.bans.use.unipban: true
  maussentials.bans:
    description: Use the whole MauBans module.
    default: OP
    children:
      maussentials.bans.use: true
      maussentials.bans.see: true
  # Teleportation permissions
  maussentials.tp.*:
    description: Use anything in the tp module
    default: OP
    children:
      maussentials.tp: true
      maussentials.tp.request: true
      maussentials.tp.accept: true
  maussentials.tp:
    description: Teleportation. Self -> Player, Self -> Coords, Player -> Player or Player -> Coords
    default: OP
  maussentials.tp.request:
    description: Request to teleport to a specific player.
    default: true
  maussentials.tp.accept:
    description: Accept or deny a teleport request
    default: true
  maussentials.tp.nodelay:
    description: Bypass the teleport delay
    default: OP