name: Maussentials
author: Tulir293
main: net.maunium.bukkit.Maussentials.Maussentials
website: http://maunium.net
version: 0.1
commands:
  mauwelcomemessage:
    description: Print the welcome message
    aliases: [welcomemessage, mauwm, wm, mauwelcomemsg, welcomemsg, mauwelcome, welcome, maumotd, motd]
  maukill:
    description: Kill a player
    aliases: [kill, mauslay, slay]
  mauuuid:
    description: "UUID tools (fetches data from Mojangs' servers)"
    aliases: [uuid, mauuuidtools, uuidtools]
  maugod:
    description: Invincibility
    aliases: [god, maunodamage, nodamage]
  maumessage:
    description: Send a private message
    aliases: [message, maumsg, msg, maupm, pm, mauprivatemessage, privatemessage]
  maureply:
    description: Reply to the last person that sent you a private message
    aliases: [reply, maur, r, maurepl, repl]
  mausocialspy:
    description: Spy on private messages
    aliases: [socialspy, mauss, ss, maumsgspy, msgspy, maupmspy, pmspy]
  maucommandspy:
    description: Spy on private messages
    aliases: [socialspy, mauss, ss, maumsgspy, msgspy, maupmspy, pmspy]
  mauseen:
    description: See info about a player
    aliases: [seen, maulastseen, lastseen, mauplayerinfo, playerinfo]
permissions:
  maussentials.welcomemessage:
    description: Print the welcome message
    default: true
  maussentials.kill:
    description: Kill a player
    default: OP
  maussentials.uuid:
    description: "UUID tools (fetches data from Mojangs' servers)"
    default: OP
  maussentials.god:
    description: Invincibility
    default: OP
  maussentials.god.others:
    description: Invincibility
    default: OP
  maussentials.message:
    description: Use the private messaging system
    default: true
  maussentials.message.color:
    description: Use colors (format codes 0-9a-f) in private messages
    default: OP
  maussentials.message.style:
    description: Use styles (format codes l-o) in private messages
    default: OP
  maussentials.message.magic:
    description: Use magic (format code k) in private messages
    default: OP
  maussentials.message.format:
    description: Use all formatting codes in private messages
    default: OP
    children: 
      maussentials.message.color: true
      maussentials.message.style: true
      maussentials.message.magic: true
  maussentials.message.spy:
    description: Spy on private messages
    default: OP
  maussentials.commandspy:
    description: Spy player commands
    default: OP
  maussentials.seen:
    description: See info about a player
    default: OP