name: Maussentials
author: Tulir293
main: net.maunium.bukkit.Maussentials.Maussentials
website: http://maunium.net
version: 0.1
depend: [SQLibrary]
commands:
  mauwelcomemessage:
    description: Print the welcome message
    aliases: [welcomemessage, mauwm, wm, mauwelcomemsg, welcomemsg, mauwelcome, welcome, maumotd, motd]
  maukill:
    description: Kill a player
    aliases: [kill, mauslay, slay]
  mauuuid:
    description: "UUID tools (fetches data from Mojangs' servers)"
    aliases: [uuid, mauuuidtools, uuidtools]
  maugod:
    description: Invincibility
    aliases: [god, maunodamage, nodamage]
  maumessage:
    description: Send a private message
    aliases: [message, maumsg, msg, maupm, pm, mauprivatemessage, privatemessage]
  maureply:
    description: Reply to the last person that sent you a private message
    aliases: [reply, maur, r, maurepl, repl]
  mausocialspy:
    description: Spy on private messages
    aliases: [socialspy, mauss, ss, maumsgspy, msgspy, maupmspy, pmspy]
  maucommandspy:
    description: Spy on private messages
    aliases: [commandspy, maucs, cs, maucmdspy, cmdspy]
  mauseen:
    description: See info about a player
    aliases: [seen, maulastseen, lastseen, mauplayerinfo, playerinfo]
  mauplugin:
    description: Reload a plugin.
    aliases: [plugin, maureloader, reloader, mauplugman, plugman, mauplug, plug]
  mauplainsay:
    description: Plain broadcast (no prefixes).
    aliases: [plainsay, maupsay, psay, maups, ps, mauplainbroadcast, plainbroadcast, maupb, pb]
  mausignedit:
    description: Edit signs
    aliases: [signedit, mause, se]
permissions:
  maussentials.welcomemessage:
    description: Print the welcome message
    default: true
  maussentials.kill:
    description: Kill a player
    default: OP
  maussentials.uuid:
    description: "UUID tools (fetches data from Mojangs' servers)"
    default: OP
  maussentials.god:
    description: Invincibility
    default: OP
  maussentials.god.others:
    description: Invincibility
    default: OP
  maussentials.message:
    description: Use the private messaging system
    default: true
  maussentials.message.spy:
    description: Spy on private messages
    default: OP
  maussentials.commandspy:
    description: Spy player commands
    default: OP
  maussentials.seen:
    description: See info about a player
    default: OP
  maussentials.plugins:
    description: See the plugin list
    default: true
  maussentials.plugin:
    description: Allow reloading plugins
    default: OP
  maussentials.plainsay:
    description: Allow use of /mauplainsay
    default: OP
  maussentials.plainsay.see:
    description: See when a plain say message is broadcasted.
    default: OP
  maussentials.sign.edit:
    description: Edit signs
    default: OP
  maussentials.sign.format.color:
    description: Color in signs
    default: OP
  maussentials.sign.format.style:
    description: Color in signs
    default: OP
  maussentials.sign.format.magic:
    description: Color in signs
    default: OP
  maussentials.sign.format:
    description: Format signs in any way
    default: OP
    children:
      maussentials.sign.format.color: true
      maussentials.sign.format.style: true
      maussentials.sign.format.magic: true